### ISSUE TITLE
Adding wdltools to conda-forge channel for easy redistribution with miniconda/anaconda

### ISSUE THREAD

**Issue by rhpvorderman** [dnanexus-rnd/wdlTools#110]
https://github.com/conda-forge/staged-recipes/pull/12233

Dear @jdidion and @orodeh ,

Thanks for the great work on wdTools. I packaged wdlTools as the wdltools conda package. This makes distribution, installation and use much easier. i.e. `conda install wdltools; wdltools <command>` instead of `wget <link to wdltools.jar>; java -jar <location of jar> <command>`. Especially remembering the location of the jar every time is not nice. This makes updating painful.

With conda this problem is solved. I have added you both as maintainers for the package. Updating is easy: a pushed tag should be automatically detected. An auto-generated PR will follow. This makes stuff easy to update. Cromwell and miniwdl are already packaged on conda-forge. I packaged miniwdl, and maintenance has been so easy there was no involvement from me needed since. 

If you don't want to maintain the package I will remove you from the list and I will maintain the package for you. If you are interested in maintaining it (i.e. you can determine when a new update is pushed to conda-forge) please state so in the above PR. It is required for the PR to be merged.

Thanks again!

**Comment by jdidion** [comment]
Fantastic, thanks! I'll take over the package.
