### ISSUE TITLE
API calls to write out WDL files

### ISSUE THREAD

**Issue by nyue** [dnanexus-rnd/wdlTools#128]
I was informed that the wdlTools Scala API has provision for writing out WDL files from a Scala program which describe the workflow via Scala data/objects.

I wasn't able to find example/tutorial Scala code in this report which illustrate them.

Some pointer to them would be very much appreciated.

Thank you.

**Comment by jdidion** [comment]
Hi @nyue, I put an example here: https://github.com/dnanexus-rnd/wdlTools/blob/develop/doc/Examples/GenerateCode.scala
