### ISSUE TITLE
Issues when cloning in a path with whitespaces

### ISSUE THREAD

**Issue by lfrancioli** [dnanexus-rnd/wdlTools#155]
Hi,

I've run into troubles with installing / running wdlTools from a path with whitespaces. 
First, ROOT_DIR was not set in the Makefile when trying to make on my MacOS system; It would set it to "".
I've replaced `ROOT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))` with `ROOT_DIR=$(shell pwd)` and it worked.
Second, almost all tests failed with `java.io.FileNotFoundException: Path does not exist`

At this point, I decided to clone wdlTools elsewhere.

Cheers,
Laurent

**Comment by jdidion** [comment]
I think the complex command is used in the case where you run `make /path/to/makefile` from a directory other than the one that contains the Makefile. It is a known issue that command doesn't handle paths with spaces. I think it's a reasonable restriction to say `make` must be run from the project folder, so I will update the build script with your change.
