### ISSUE TITLE
AST for multiple consecutive operations is incorrect

### ISSUE THREAD

**Issue by jdidion** [dnanexus-rnd/wdlTools#16]
```wdl
Int x = i + i + i
```

Expected: `ExprAdd(ExprAdd(ExprIdentifier(i),ExprIdentifier(i)), ExprIdentifier(i))`

Actual: `ExprAdd(ExprIdentifier(i),ExprIdentifier(i))`

Possible fixes:

1. Generate nested structure as above
2. Make the value of operation types that may be chained a sequence rather than just a and b - this is nicer at least for formatting, because otherwise I need to detect consecutive uses of the same operation and merge them together

**Comment by jdidion** [comment]
I added branch bug/16-chained-operations with a test case

**Comment by orodeh** [comment]
I am working on it.

**Comment by orodeh** [comment]
So far, I've removed potential problems from the scala parser, and found out that if you add braces then things work as expected. So,  `(i + i) + i` works, but `i + i + i` does not. I have asked Patrick if this is a problem in his wdl4j (WDL for Java) code, which uses the same parser.

**Comment by orodeh** [comment]
A fix is on master branch.
