### ISSUE TITLE
Missing coercion of V_Directory

### ISSUE THREAD

**Issue by jdidion** [dnanexus-rnd/wdlTools#226]
In `wdlTools.eval.Coercion`, around line 55, the coercion `case (WdlTypes.T_Directory, d: V_Directory) => d` is missing.

To reproduce, create a workflow that takes a struct like this as input:

```
struct Index {
    Directory? index_dir
    String? prefix
}
```

**Comment by jdidion** [comment]
@Gvaihir I just ran into this issue again. I submitted a PR.

**Comment by Gvaihir** [comment]
@jdidion Thanks, I have it in my sprint (sorry for not reacting earlier it was low priority class). I will create a unit test in the PR and merge by EOD

**Comment by jdidion** [comment]
@Gvaihir thanks! No worries. It is only now becoming urgent because we need to start running workflows on DNAnexus.

**Comment by Gvaihir** [comment]
I will open our own PR for internal tracking purposes with your fix and added regression test + other fluff
#232
