### ISSUE TITLE
How to call womtool in a Java web project.

### ISSUE THREAD

**Issue by wsl-ylhy** [dnanexus-rnd/wdlTools#247]
Hello, I saw that you have packages stored in the Maven repository. Can I call the API in a Java web project?

**Comment by Gvaihir** [comment]
We stopped publishing on Maven after 0.17.1, using GH packages now. Whether you can - that's up to how you designed your project. wdlTools is a scala library, check the compatibility for your code when injecting dependencies in the Java source. Good luck!
