### ISSUE TITLE
Handle null value in typechecker

### ISSUE THREAD

**Issue by jdidion** [dnanexus-rnd/wdlTools#35]
See discussion w/ Patrick here: https://github.com/openwdl/wdl/pull/361

It is part of the 1.0 spec that null is a valid value in meta sections, but Patrick argues that this should be handled as a special case by tools. So the parser recognizes null as an identifier, but the typechecker should treat null as a valid identifier within the meta sections even if there is no declaration for an input/variable named 'null'.

**Comment by orodeh** [comment]
Implemented and on master.
